apiVersion: v1
#apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: epc
  labels:
    env: test
    name: epc
spec:
  containers:
    - name: hss
      image : moffzilla/oai-hss:v01
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
#      ports:
#        - hostIP: 172.19.0.10      
    - name: mme
      image: moffzilla/oai-hss:v01
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
#      ports:
#        - hostIP: 172.19.0.20
    - name: spgw
      image: moffzilla/oai-spgw:v01
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
#      ports:
#        - hostIP: 172.19.0.30
# If you want to provide a password for accessing images
#  imagePullSecrets:
#    - name: myregistrykey
